config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'reviews/index'
  end
  devise_for :users,controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'}


  devise_for :admin,controllers: {
  #後で消す
  registrations: "admin/registrations",
  sessions: "admin/sessions"}

  devise_for :bars,controllers: {
  registrations: "bar/registrations",
  sessions: 'bar/sessions'}

  namespace :admin do
  root to: "tweets#index"
  resources :genres, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
    resources :tweet_comments, only: [:destroy]
    end
  resources :users, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
    resources :reviews, only: [:destroy, :index]
    end
  end

  namespace :bar do
  root to: "tweets#index"
  get '/bars/unsubscribe' => 'bars#unsubscribe'
  patch '/bars/withdraw' => 'bars#withdraw'
  resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  end

  scope module: :user do

    root to: "homes#top"
    get 'homes/about'
    get "/users/show" => "users#show", as: "user"
    patch 'users/update' => "users#update"
    get 'users/confirm' => "users#confirm"
    get '/search', to: 'searches#search'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'

   resources :genres, only: [:index, :show]
   resources :users, only: [:new, :index, :edit, :destroy] do
     member do
     get :favorites
     end
   end
   resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
     resources :reviews, only: [:create, :destroy, :index]
    end
   resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :tweet_comments, only: [:create, :destroy]
   end
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bar.rb
class Bar < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :reviews, dependent: :destroy

def self.looks(word)
  # ヒントとしてはスペースを除外したい or スペースのみってのを検知する
 if word == "" # 実はスペースだけのケースがあり得る....
    @bars = Bar.all
 else
    @bars = Bar.where("bar_name LIKE?","%#{word}%")
 end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :tweet_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :reviews, dependent: :destroy
   
end

app/controllers/admin/bars_controller.rb
class Admin::BarsController < ApplicationController
  def index
    @bars = Bar.all
  end

  def new
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def show
    @bar = Bar.find(params[:id])
  end
  
  def update
    @bar = Bar.find(params[:id])
    @bar.present?
    if @bar.update(bar_params)
    redirect_to admin_bar_path(@bar.id)
    else
    render :edit
    end
  end
  
  private

  def bar_params
    params.require(:bar).permit(:bar_name, :bar_tel, :address, :post_code, :email, :is_deleted)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to admin_user_path(@user.id)
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name_first, :name_second, :name_firdt_rubi, :name_second_rubi, :tel, :email, :is_deleted)
  end

end

app/controllers/bar/bars_controller.rb
class Bar::BarsController < ApplicationController
  def index
    @bars = Bar.all
  end

  def new
    @bar = Bar.new
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def show
    @bar = Bar.find(params[:id])
  end

  def update
    @bar = Bar.find(params[:id])
    @bar.present?
    if @bar.update(bar_params)
    redirect_to bar_bar_path(@bar.id)
    else
    render :edit
    end
  end
  
  def unsubscribe
    @bar = current_bar
  end

  def withdraw
    @bar = current_bar
    @bar.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  private

  def bar_params
    params.require(:bar).permit(:bar_name, :bar_tel, :address, :post_code, :email, :is_deleted)
  end

end

app/controllers/bar/confirmations_controller.rb
# frozen_string_literal: true

class Bar::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/bar/homes_controller.rb
class Bar::HomesController < ApplicationController
  def top
    @bar = current_bar
    @review = Review.new
  end
end

app/controllers/bar/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Bar::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/bar/passwords_controller.rb
# frozen_string_literal: true

class Bar::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/bar/registrations_controller.rb
# frozen_string_literal: true

class Bar::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/bar/sessions_controller.rb
# frozen_string_literal: true

class Bar::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/bar/tweets_controller.rb
class Bar::TweetsController < ApplicationController
  def index
    @tweets = current_bar.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    #アソシエーションする
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.bar_id = current_bar.id
    if @tweet.save
    redirect_to bar_tweets_path
    else
    render :new
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.present?
    if @tweet.update(tweet_params)
    redirect_to bar_tweets_path
    else
    render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to bar_tweets_path
  end

   private

  def tweet_params
  params.require(:tweet).permit(:title, :body, :genre_id, :image)
  end

  def set_genre
  @genres = Genre.all
  end

end

app/controllers/bar/unlocks_controller.rb
# frozen_string_literal: true

class Bar::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/bars_controller.rb
class User::BarsController < ApplicationController

  def index
    @bars = Bar.all
  end

  def show
    @bar = Bar.find(params[:id])
    @tweets = @bar.tweets
    @review = Review.new
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_user.favorites.new(tweet_id: tweet.id)
    favorite.save
    redirect_back fallback_location: tweets_path
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_user.favorites.find_by(tweet_id: tweet.id)
    favorite.destroy
    redirect_back fallback_location: tweets_path
  end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @tweets = @genre.tweets
  end


private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @genres = Genre.all
  end

  def about
    @genres = Genre.all
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/views/user/bars/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8 offset-md-2">

  <h5>居酒屋一覧</h5>
    <table class="table table-striped">
      <tr>
      <th>店名</th>
      <th>電話番号</th>
      <th>住所</th>
      <td></td>
      <td></td>
     </tr>
   <% @bars.each do |f| %>
      <tr>
        <td><%= link_to f.bar_name, bar_path(f.id)%></td>
        <td><%= f.bar_tel %></td>
        <td><%= f.address %></td>
        <td>
        <%= link_to bar_reviews_path(f.id) do %>
        レビュー<%= f.reviews.count %> 件
        <% end %>
        </td>
        <td>
        <div class="average-score-display">評価：<%= f.reviews.average(:star).to_f.round(1) %> / 5</div>
 </td>
      </tr>
　 <% end %>
   </table>
  </div>
 </div>
</div>

app/views/user/bars/new.html.erb
 <p>レビュー件数：<%= @bar.reviews.count %></p>

    <% @bar.reviews.each do |review| %>
    <%= review.user.name_first %>
    <%= review.created_at.strftime('%Y/%m/%d') %>
    <%= review.post %>

    <div class="review-rating" data-score="<%= review.star %>">評価：<div id="review-star-<%= review.id %>"></div></div>
    <% if review.user == current_user %>
      <%= link_to "削除", bar_review_path(review.bar, review), method: :delete %>
    <% end %>
     <script>
    $("#review-star-<%= review.id %>").raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        score: "<%= review.star %>",
        readOnly: true
    });
</script>
    <% end %>
  </div>

   <div>
    <%= form_with model: [@bar, @review] do |f| %>
    <%= f.text_area :post, rows: '7', placeholder: "レビューをここに" %>

    <div id="rating-form">
        <label>評価：</label>
        <%# scoreNameの値をhidden_fieldでカラムに送っている %>
        <%= f.hidden_field :star, :value => 'score' %>
    </div>

    <%= f.submit "送信する" %>
    <% end %>

    <script>
    $('#rating-form').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        scoreName: 'review[star]'
    });
</script>

app/views/user/bars/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8 offset-md-2">
    <h5><strong><%= @bar.bar_name %>の詳細</strong></h5>
    <p>
      <%= link_to(bar_reviews_path(@bar.id), class:"text-dark") do %>
      レビュー件数：<%= @bar.reviews.count %>
      <% end %>
    </p>

    <p>レビュー評価：<%= @bar.reviews.count %></p>

   <div>
    <%= form_with model: [@bar, @review] do |f| %>
    <%= f.text_area :post, rows: '7', placeholder: "レビューをここに" %>

    <div id="rating-form">
        <label>評価：</label>
        <%# scoreNameの値をhidden_fieldでカラムに送っている %>
        <%= f.hidden_field :star, :value => 'score' %>
    </div>

    <%= f.submit "送信する" %>
    <% end %>

    <script>
    $('#rating-form').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        scoreName: 'review[star]'
    });
</script>
  </div>
 </div>
</div>


   <% @tweets.each do |f| %>
<div class="card w-50 mx-auto mt-4 shadow-lg">
 <div class="card-body">
  <div class="row">
   <div class="col-md-8 offset-md-2">

      <p class="card-title">
       <%= link_to(tweet_path(f.id), class:"text-dark") do %>
       <strong><i class="fa fa-beer"></i><span> <%= f.bar.bar_name %></span></strong>
       <% end %>
      </p>
      <p class="card-text"><%= f.title %></p>
      <p class="card-text"><%= f.body %></p>
       <p class="card-text"><% if f.image.attached? %>
        <%= image_tag f.image, size: "200x200" %>
       <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
       <% end %></p>
      <span>
        <i class="fas fa-comment"></i> <%= "#{f.tweet_comments.count} コメント" %> ｜
      </span>
      <span>
        <% if f.favorited_by?(current_user) %>
          <td>
             <%= link_to tweet_favorites_path(f), method: :delete do %>
              ♥<%= f.favorites.count %> いいね
              <% end %>
          </td>
        <% else %>
          <td>
              <%= link_to tweet_favorites_path(f), method: :post do %>
              ♡<%= f.favorites.count %> いいね
              <% end %>
          </td>
        <% end %>
      </span>
   </div>
  </div>
 </div>
</div>
   <% end %>