config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'reviews/index'
  end
  devise_for :users,controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'}


  devise_for :admin,controllers: {
  #後で消す
  registrations: "admin/registrations",
  sessions: "admin/sessions"}

  devise_for :bars,controllers: {
  registrations: "bar/registrations",
  sessions: 'bar/sessions'}

  namespace :admin do
  root to: "tweets#index"
  resources :genres, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
    resources :tweet_comments, only: [:destroy]
    end
  resources :users, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
    resources :reviews, only: [:destroy, :index]
    end
  end

  namespace :bar do
  root to: "tweets#index"
  get '/bars/unsubscribe' => 'bars#unsubscribe'
  patch '/bars/withdraw' => 'bars#withdraw'
  resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  end

  scope module: :user do

    root to: "homes#top"
    get 'homes/about'
    get "/users/show" => "users#show", as: "user"
    patch 'users/update' => "users#update"
    get 'users/confirm' => "users#confirm"
    get '/search', to: 'searches#search'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'

   resources :genres, only: [:index, :show]
   resources :users, only: [:new, :index, :edit, :destroy] do
     member do
     get :favorites
     end
   end
   resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
     resources :reviews, only: [:create, :destroy, :index]
    end
   resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :tweet_comments, only: [:create, :destroy]
   end
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord

belongs_to :bar
belongs_to :genre
has_many :tweet_comments, dependent: :destroy
has_many :favorites, dependent: :destroy
has_one_attached :image

 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 def self.looks(word)
  if word == ""
   @tweet = Tweet.all
  else
   @tweet = Tweet.where("title LIKE?","%#{word}%")
  end
 end
end
#投稿内容も入れる

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :tweet_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :reviews, dependent: :destroy
   
end

app/controllers/admin/tweets_controller.rb
class Admin::TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
  end

  def edit
  end

  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to admin_tweets_path
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to admin_user_path(@user.id)
    else
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name_first, :name_second, :name_firdt_rubi, :name_second_rubi, :tel, :email, :is_deleted)
  end

end

app/controllers/bar/tweets_controller.rb
class Bar::TweetsController < ApplicationController
  def index
    @tweets = current_bar.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    #アソシエーションする
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.bar_id = current_bar.id
    if @tweet.save
    redirect_to bar_tweets_path
    else
    render :new
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.present?
    if @tweet.update(tweet_params)
    redirect_to bar_tweets_path
    else
    render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to bar_tweets_path
  end

   private

  def tweet_params
  params.require(:tweet).permit(:title, :body, :genre_id, :image)
  end

  def set_genre
  @genres = Genre.all
  end

end

app/controllers/user/bars_controller.rb
class User::BarsController < ApplicationController

  def index
    @bars = Bar.all
  end

  def show
    @bar = Bar.find(params[:id])
    @tweets = @bar.tweets
    @review = Review.new
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_user.favorites.new(tweet_id: tweet.id)
    favorite.save
    redirect_back fallback_location: tweets_path
  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_user.favorites.find_by(tweet_id: tweet.id)
    favorite.destroy
    redirect_back fallback_location: tweets_path
  end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @tweets = @genre.tweets
  end


private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @genres = Genre.all
  end

  def about
    @genres = Genre.all
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  def create
    bar = Bar.find(params[:bar_id])
    review = current_user.reviews.new(review_params)
    #下記２つの省略型
    #comment = PostComment.new(post_comment_params)
    #comment.user_id = current_user.id
    review.bar_id = bar.id
    review.save
    redirect_to bar_path(bar)
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to bar_path(params[:bar_id])
  end
  
  def index
     @bar = Bar.find(params[:bar_id])
     @reviews = @bar.reviews
  end

  private

  def review_params
    params.require(:review).permit(:post, :star)
  end

end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController

  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "Bar"
      @bars = Bar.looks(params[:word])
    else
      @tweets = Tweet.looks( params[:word])
    end
  end

end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/tweet_comments_controller.rb
class User::TweetCommentsController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = current_user.tweet_comments.new(tweet_comment_params)
    #下記２つの省略型
    #comment = PostComment.new(post_comment_params)
    #comment.user_id = current_user.id
    comment.tweet_id = tweet.id
    comment.save
    redirect_to tweet_path(tweet)
  end
  
  def destroy
    TweetComment.find(params[:id]).destroy
    redirect_to tweet_path(params[:tweet_id])
  end

  private

  def tweet_comment_params
    params.require(:tweet_comment).permit(:comment)
  end

end

app/controllers/user/tweets_controller.rb
class User::TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def edit
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :set_user, only: [:favorites]


  def index
  end

  def new
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
    redirect_to user_path
    else
    render :edit
    end
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:tweet_id)
    @favorite_tweets = Tweet.find(favorites)
  end

  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name_first, :name_second, :name_firdt_rubi, :name_second_rubi, :tel, :email, :is_deleted)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/user/tweets/edit.html.erb
<h1>User::Tweets#edit</h1>
<p>Find me in app/views/user/tweets/edit.html.erb</p>

app/views/user/tweets/index.html.erb
<% @tweets.each do |f| %>
<div class="card w-50 mx-auto mt-4 shadow-lg">
 <div class="card-body">
  <div class="row">
   <div class="col-md-8 offset-md-2">

     <p class="card-title">
       <%= link_to(tweet_path(f.id), class:"text-dark") do %>
       <strong><i class="fa fa-beer"></i><span> <%= f.bar.bar_name %></span></strong>
       <% end %>
     </p>
     <p class="card-text"><%= f.title %></p>
     <p class="card-text"><%= f.body %></p>
      <p class="card-text"><% if f.image.attached? %>
        <%= image_tag f.image, size: "200x200" %>
       <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
       <% end %></p>

     <span><i class="fas fa-comment"></i> <%= "#{f.tweet_comments.count} コメント" %> ｜ </span>
     <span><% if f.favorited_by?(current_user) %>
       <td>
        <%= link_to tweet_favorites_path(f), method: :delete do %>
        <i class="text-danger">♥</i><%= f.favorites.count %> いいね
        <% end %>
       </td>
        <% else %>
       <td>
        <%= link_to tweet_favorites_path(f), method: :post do %>
        ♡<%= f.favorites.count %> いいね
        <% end %>
       </td>
        <% end %>
     </span>
   </div>
  </div>
 </div>
</div>
<% end %>

app/views/user/tweets/new.html.erb
<h1>User::Tweets#new</h1>
<p>Find me in app/views/user/tweets/new.html.erb</p>

app/views/user/tweets/show.html.erb
 <h4><%= @tweet.bar.bar_name %>の投稿一覧</h4>
<div class="card w-50 mx-auto mt-4 shadow-lg">
 <div class="card-body">
  <div class="row">
   <div class="col-md-8 offset-md-2">
     <strong><i class="fa fa-beer"></i><span> <%= @tweet.bar.bar_name %></span></strong>
     <p class="card-text"><%= @tweet.title %></p>
     <p class="card-text"><%= @tweet.body %></p>
      <p class="card-text"><% if @tweet.image.attached? %>
        <%= image_tag @tweet.image, size: "200x200" %>
       <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
       <% end %></p>
     <p class="card-text"><%= @tweet.genre.name %></p>
      <span><i class="fas fa-comment"></i> <%= "#{@tweet.tweet_comments.count} コメント" %> ｜</span>
      <span>
         <% if @tweet.favorited_by?(current_user) %>
           <%= link_to tweet_favorites_path(@tweet), method: :delete do %>
           <i class="text-danger">♥</i><%= @tweet.favorites.count %> いいね
           <% end %>
         <% else %>
           <%= link_to tweet_favorites_path(@tweet), method: :post do %>
           ♡<%= @tweet.favorites.count %> いいね
           <% end %>
         <% end %>
     </span>


   </div>
  </div>
 </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
     <p></p>

 <div>
    <%= form_with model: [@tweet, @tweet_comment] do |f| %>
    <%= f.text_area :comment, rows: '7', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
    <% end %>
  </div>

  </div>
 </div>
</div>

<div class="card w-50 mx-auto mt-4 shadow-lg">
 <div class="card-body">
  <div class="row">
   <div class="col-md-6 offset-md-3">
      <h4>コメント一覧</h4>
        <% @tweet.tweet_comments.each do |tweet_comment| %>
         <p><%= tweet_comment.user.name_first %>
        <%= tweet_comment.created_at.strftime('%Y/%m/%d') %><p>
        <p>コメント：<%= tweet_comment.comment %></p>
        <% if tweet_comment.user == current_user %>
         <%= link_to "削除", tweet_tweet_comment_path(tweet_comment.tweet, tweet_comment), method: :delete %>
         <% end %>
        <p>.................</p>
       <% end %>
   </div>
  </div>
 </div>
</div>