config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'reviews/index'
  end
  devise_for :users,controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'}


  devise_for :admin,controllers: {
  #後で消す
  registrations: "admin/registrations",
  sessions: "admin/sessions"}

  devise_for :bars,controllers: {
  registrations: "bar/registrations",
  sessions: 'bar/sessions'}

  namespace :admin do
  root to: "tweets#index"
  resources :genres, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
    resources :tweet_comments, only: [:destroy]
    end
  resources :users, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
    resources :reviews, only: [:destroy, :index]
    end
  end

  namespace :bar do
  root to: "tweets#index"
  get '/bars/unsubscribe' => 'bars#unsubscribe'
  patch '/bars/withdraw' => 'bars#withdraw'
  resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy]
  end

  scope module: :user do

    root to: "homes#top"
    get 'homes/about'
    get "/users/show" => "users#show", as: "user"
    patch 'users/update' => "users#update"
    get 'users/confirm' => "users#confirm"
    get '/search', to: 'searches#search'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'

   resources :genres, only: [:index, :show]
   resources :users, only: [:new, :index, :edit, :destroy] do
     member do
     get :favorites
     end
   end
   resources :bars, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
     resources :reviews, only: [:create, :destroy, :index]
    end
   resources :tweets, only: [:new, :index, :edit, :show, :create, :update, :destroy] do
     resource :favorites, only: [:create, :destroy]
     resources :tweet_comments, only: [:create, :destroy]
   end
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bar.rb
class Bar < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :reviews, dependent: :destroy

def self.looks(word)
  # ヒントとしてはスペースを除外したい or スペースのみってのを検知する
 if word == "" # 実はスペースだけのケースがあり得る....
    @bars = Bar.all
 else
    @bars = Bar.where("bar_name LIKE?","%#{word}%")
 end
end
end

app/models/tweet.rb
class Tweet < ApplicationRecord

belongs_to :bar
belongs_to :genre
has_many :tweet_comments, dependent: :destroy
has_many :favorites, dependent: :destroy
has_one_attached :image

 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 def self.looks(word)
  if word == ""
   @tweet = Tweet.all
  else
   @tweet = Tweet.where("title LIKE?","%#{word}%")
  end
 end
end
#投稿内容も入れる

app/controllers/admin/bars_controller.rb
class Admin::BarsController < ApplicationController
  def index
    @bars = Bar.all
  end

  def new
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def show
    @bar = Bar.find(params[:id])
  end
  
  def update
    @bar = Bar.find(params[:id])
    @bar.present?
    if @bar.update(bar_params)
    redirect_to admin_bar_path(@bar.id)
    else
    render :edit
    end
  end
  
  private

  def bar_params
    params.require(:bar).permit(:bar_name, :bar_tel, :address, :post_code, :email, :is_deleted)
  end
  
end

app/controllers/admin/tweets_controller.rb
class Admin::TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
  end

  def edit
  end

  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to admin_tweets_path
  end
  
end

app/controllers/bar/bars_controller.rb
class Bar::BarsController < ApplicationController
  def index
    @bars = Bar.all
  end

  def new
    @bar = Bar.new
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def show
    @bar = Bar.find(params[:id])
  end

  def update
    @bar = Bar.find(params[:id])
    @bar.present?
    if @bar.update(bar_params)
    redirect_to bar_bar_path(@bar.id)
    else
    render :edit
    end
  end
  
  def unsubscribe
    @bar = current_bar
  end

  def withdraw
    @bar = current_bar
    @bar.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  private

  def bar_params
    params.require(:bar).permit(:bar_name, :bar_tel, :address, :post_code, :email, :is_deleted)
  end

end

app/controllers/bar/confirmations_controller.rb
# frozen_string_literal: true

class Bar::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/bar/homes_controller.rb
class Bar::HomesController < ApplicationController
  def top
    @bar = current_bar
    @review = Review.new
  end
end

app/controllers/bar/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Bar::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/bar/passwords_controller.rb
# frozen_string_literal: true

class Bar::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/bar/registrations_controller.rb
# frozen_string_literal: true

class Bar::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/bar/sessions_controller.rb
# frozen_string_literal: true

class Bar::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/bar/tweets_controller.rb
class Bar::TweetsController < ApplicationController
  def index
    @tweets = current_bar.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    #アソシエーションする
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.bar_id = current_bar.id
    if @tweet.save
    redirect_to bar_tweets_path
    else
    render :new
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.present?
    if @tweet.update(tweet_params)
    redirect_to bar_tweets_path
    else
    render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to bar_tweets_path
  end

   private

  def tweet_params
  params.require(:tweet).permit(:title, :body, :genre_id, :image)
  end

  def set_genre
  @genres = Genre.all
  end

end

app/controllers/bar/unlocks_controller.rb
# frozen_string_literal: true

class Bar::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/bars_controller.rb
class User::BarsController < ApplicationController

  def index
    @bars = Bar.all
  end

  def show
    @bar = Bar.find(params[:id])
    @tweets = @bar.tweets
    @review = Review.new
  end

end

app/controllers/user/tweets_controller.rb
class User::TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def edit
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
  end
end

app/helpers/admin/bars_helper.rb
module Admin::BarsHelper
end

app/helpers/admin/tweets_helper.rb
module Admin::TweetsHelper
end

app/helpers/bar/bars_helper.rb
module Bar::BarsHelper
end

app/helpers/bar/homes_helper.rb
module Bar::HomesHelper
end

app/helpers/bar/tweets_helper.rb
module Bar::TweetsHelper
end

app/views/bar/tweets/edit.html.erb
<!DOCTYPE html>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>投稿編集</h2>
      <%= form_with model: @tweet, url: bar_tweet_path(@tweet.id), method: :patch do |f|  %>
      <tbody>
        <tr>
          <th>
            <h5>タイトル
            　<%= f.text_field :title %>
            </h5>
          </th>
          <th>
            <h5>投稿内容
            　<%= f.text_field :body, class:"w-75" %>
            </h5>
          </th>
          <th>
            <h5>ジャンル
            　<%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "---"}, class:"w-75" %>
            </h5>
          </th>
          <%= f.submit '変更を保存', class:"btn btn-success" %>
      <% end %>
      </tbody>
    </div>
  </div>
</div>

app/views/bar/tweets/index.html.erb
<!DOCTYPE html>
<div class="row">
   <div class="col-md-8 offset-md-2">
    <h4><%=current_bar.bar_name %>さんのマイページ</h4>
    <%= link_to(bar_bar_path(current_bar), class:"text-dark") do %>
       <strong><i class="fa fa-beer"></i><span> <%= current_bar.bar_name %></span></strong>
       <% end %>

<% @tweets.each do |f| %>
<div class="card w-50 mx-auto mt-4 shadow-lg">
 <div class="card-body">
  <div class="row">
   <div class="col-md-8 offset-md-2">

     <p class="card-title">
       <%= link_to(bar_tweet_path(f.id), class:"text-dark") do %>
       <strong><i class="fa fa-beer"></i><span> <%= f.bar.bar_name %></span></strong>
       <% end %>
     </p>
     <p class="card-text"><%= f.title %></p>
     <p class="card-text"><%= f.body %></p>
     <p class="card-text"><%= f.genre.name %></p>
     <p class="card-text">
       <% if f.image.attached? %>
        <%= image_tag f.image, size: "200x200" %>
       <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
       <% end %></p>
      <span><i class="fas fa-comment"></i> <%= "#{f.tweet_comments.count} コメント" %> ｜ </span>
      <span>♡<%= f.favorites.count %> いいね</span>

   </div>
  </div>
 </div>
</div>
<% end %>

app/views/bar/tweets/new.html.erb
<!DOCTYPE html>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>新規投稿</h2>
<%# if @tweet.errors.any? %>
  <%#= @tweet.errors.count件の未記入がありました %>
  <%#<ul>
    <% @tweet.errors.full_messages.each do |message| %>
      <%#<li><%= message %>
    <%# end %>

<%# end %>
            <%= form_with model: @tweet, url: bar_tweets_path, method: :post do |tweet| %>
        <tbody>
          <tr>
            <td>
              <h5>
              タイトル
              　<%= tweet.text_field :title %>
              </h5>
            </td>

            <td>
              <h5>
              投稿内容
                　<%= tweet.text_area :body %>
              </h5>
            </td>

            <td>
              <h5>
                ジャンル
                　<%= tweet.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "---"}, class:"w-50" %>
              </h5>
            </td>
            
            <td>
              <h5>
                画像
                <%= tweet.file_field :image, accept: "image/*" %>
              </h5>
            </td>

         </tr>
               <%= tweet.submit '新規登録', class:"btn btn-success" %>
               <% end %>
        </tbody>
    </div>
  </div>
</div>

app/views/bar/tweets/show.html.erb
<div class="card w-50 mx-auto mt-4 shadow-lg">
 <div class="card-body">
  <div class="row">
   <div class="col-md-8 offset-md-2">
      <h4>投稿詳細</h4>
     <p class="card-text"><%= @tweet.title %></p>
     <p class="card-text"><%= @tweet.body %></p>
     <p class="card-text"><%= @tweet.genre.name %></p>
      <span><i class="fas fa-comment"></i> <%= "#{@tweet.tweet_comments.count} コメント" %> ｜ </span>
      <span>♡<%= @tweet.favorites.count %> いいね</span>
      </tr>
      <% if @tweet.bar == current_bar %>
            <td><%= link_to '編集', edit_bar_tweet_path(@tweet), class: "btn btn-sm btn-success edit_tweet_#{@tweet.id}" %></td>
            <td>
            <%= link_to "削除", bar_tweet_path, method: :delete,class: "btn btn-sm btn-danger" %>
           </td>
          <% end %>
   </div>
  </div>
 </div>
</div>

<div class="card w-50 mx-auto mt-4 shadow-lg">
 <div class="card-body">
  <div class="row">
   <div class="col-md-6 offset-md-3">
      <h4>コメント一覧</h4>
    <% @tweet.tweet_comments.each do |tweet_comment| %>
    <p><%= tweet_comment.user.name_first %>|<%= tweet_comment.created_at.strftime('%Y/%m/%d') %></p>
    <p><%= tweet_comment.comment %></p>
    <p>.................</p>
    <% end %>
   </div>
  </div>
 </div>
</div>